global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"

scrape_configs:

  # - job_name: 'nodeexporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['nodeexporter:9100']
  #       labels:
  #         instance: 'local'

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']


  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-remote'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['135.181.115.95:9100']
        labels:
          instance: 'remote'

  - job_name: 'cad-remote'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['135.181.115.95:8080']

  - job_name: 'node-remote-dev'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['95.217.105.228:9100']
        labels:
          instance: 'dev'

  - job_name: 'cad-remote-dev'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['95.217.105.228:8080']
        labels:
          instance: 'dev'


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

