server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://135.181.115.95:3100/loki/api/v1/push

scrape_configs:
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - 135.181.115.95:3100
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log