version: '2.1'

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://135.181.115.95:3100/loki/api/v1/push"

networks:
  web:
    external: true

services:

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - web